version: 2
registries:
  npm-registry:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_ACCESS_TOKEN}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'birotaio/web'
    groups:
      dependencies:
        dependency-type: 'production'
      dev-dependencies:
        dependency-type: 'development'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
