/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FAutocomplete: typeof import('./src/components/form/FAutocomplete.vue')['default']
    FAvatar: typeof import('./src/components/FAvatar.vue')['default']
    FBackgroundImage: typeof import('./src/components/FBackgroundImage.vue')['default']
    FBreadcrumbs: typeof import('./src/components/FBreadcrumbs.vue')['default']
    FButton: typeof import('./src/components/FButton.vue')['default']
    FButtonLink: typeof import('./src/components/router/FButtonLink.vue')['default']
    FCard: typeof import('./src/components/FCard.vue')['default']
    FCheckbox: typeof import('./src/components/form/FCheckbox.vue')['default']
    FCountrySelect: typeof import('./src/components/form/FCountrySelect.vue')['default']
    FCreditCardIcon: typeof import('./src/components/FCreditCardIcon.vue')['default']
    FCreditCardInput: typeof import('./src/components/form/FCreditCardInput.vue')['default']
    FDigitsInput: typeof import('./src/components/form/FDigitsInput.vue')['default']
    FDivider: typeof import('./src/components/FDivider.vue')['default']
    FExpandable: typeof import('./src/components/FExpandable.vue')['default']
    FField: typeof import('./src/components/form/FField.vue')['default']
    FFieldHint: typeof import('./src/components/form/FFieldHint.vue')['default']
    FFieldLabel: typeof import('./src/components/form/FFieldLabel.vue')['default']
    FFileUpload: typeof import('./src/components/form/FFileUpload.vue')['default']
    FFlagIcon: typeof import('./src/components/FFlagIcon.vue')['default']
    FForm: typeof import('./src/components/form/FForm.vue')['default']
    FGrid: typeof import('./src/components/FGrid.vue')['default']
    FGridItem: typeof import('./src/components/FGridItem.vue')['default']
    FIcon: typeof import('./src/components/FIcon.vue')['default']
    FImage: typeof import('./src/components/FImage.vue')['default']
    FInput: typeof import('./src/components/form/FInput.vue')['default']
    FLink: typeof import('./src/components/FLink.vue')['default']
    FLoader: typeof import('./src/components/FLoader.vue')['default']
    FLocaleSelect: typeof import('./src/components/form/FLocaleSelect.vue')['default']
    FLogo: typeof import('./src/components/FLogo.vue')['default']
    FLogoAnimatable: typeof import('./src/components/FLogoAnimatable.vue')['default']
    FMenu: typeof import('./src/components/FMenu.vue')['default']
    FPhoneInput: typeof import('./src/components/form/FPhoneInput.vue')['default']
    FPopup: typeof import('./src/components/FPopup.vue')['default']
    FProgressBar: typeof import('./src/components/FProgressBar.vue')['default']
    FRadio: typeof import('./src/components/form/FRadio.vue')['default']
    FRadioGroup: typeof import('./src/components/form/FRadioGroup.vue')['default']
    FRouterLink: typeof import('./src/components/router/FRouterLink.vue')['default']
    FSelect: typeof import('./src/components/form/FSelect.vue')['default']
    FSkeleton: typeof import('./src/components/FSkeleton.vue')['default']
    FSvgImage: typeof import('./src/components/FSvgImage.vue')['default']
    FTextarea: typeof import('./src/components/form/FTextarea.vue')['default']
    FTextContent: typeof import('./src/components/FTextContent.vue')['default']
    FToggle: typeof import('./src/components/form/FToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
