export const typographies = [
  'bigger-1',
  'bigger-2',
  'bigger-3',
  'bigger-4',
  'heading-1',
  'heading-2',
  'heading-3',
  'heading-4',
  'heading-5',
  'heading-6',
  'overline',
  'subtitle-1',
  'subtitle-2',
  'body-1',
  'body-2',
  'caption',
] as const;
