name: Build and Deploy
on:
  push:
    branches:
      - master
      - fix-storybook-build
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Node setup 📦
        uses: actions/setup-node@v4
        with:
          node-version: 22.21.1

      - name: Authenticate with PNPM 🔑
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare PNPM
        run: corepack prepare pnpm@10.11.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm build:sb

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'storybook-static'

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
